import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavbarComponent from "../components/Navbar";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";

export default function Home() {
  const userSelector = useSelector((state) => state.auth);
  const router = useRouter();
  useEffect(() => {
    if (!userSelector?.id) {
      router.push("/auth/login");
    } else {
      router.push("/home");
    }
  }, [userSelector?.id]);

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <NavbarComponent />
    </>
  );
}
